//
//  NSMutableData_LanguageLayout.h
//  ezV
//
//  Created by Duong on 6/11/13.
//  Copyright (c) 2013 ezV. All rights reserved.
//

#define DATA_LABEL_EMAIL_KEY 0
#define DATA_LABEL_PASS_KEY 1
#define DATA_LABEL_REPASS_KEY 2
#define DATA_LABEL_FULLNAME_KEY 3
#define DATA_LABEL_USERNAME_KEY 4
#define DATA_LOGIN_KEY  5
#define DATA_REGIST_KEY 6
#define DATA_CACEL_KEY 7
#define DATA_FINISH_KEY 8
#define DATA_STUDY_KEY 9
#define DATA_DOTEST_KEY 10
#define DATA_HELP_KEY 11
#define DATA_SETTING_KEY 12
#define DATA_LISTOFCOURSE_KEY 13
#define DATA_INTRODUCTION_KEY 14
#define DATA_ALERT_KEY 15
#define DATA_REMEMBER_KEY 16
#define DATA_MENUALERTMESS_KEY 17
#define DATA_BACK_KEY 18
#define DATA_RESGISTERVCTITLE_KEY 19
#define DATA_VIEWINFOCURSE_KEY 20
#define DATA_SELECTBUTTON_KEY 21